# Generated by Django 5.2.7 on 2025-11-01 00:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('shipping_mark', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('arrived', 'Arrived(China)'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('not_received', 'Not Received'), ('vessel', 'On The Vessel'), ('clearing', 'Clearing'), ('arrived', 'Arrived(Ghana)'), ('off_loading', 'Of Loading'), ('pick_up', 'Pick up')], default='pending', max_length=20)),
                ('cbm', models.DecimalField(decimal_places=3, help_text='Cubic meters (e.g., 1.234)', max_digits=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(blank=True, default='', help_text='Optional next action (e.g., hold, release, notify)', max_length=120)),
            ],
            options={
                'verbose_name': 'Tracking',
                'verbose_name_plural': 'Trackings',
                'ordering': ['-date_added'],
            },
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_login',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='last login'),
        ),
    ]
