# Generated by Django 5.2.7 on 2025-11-01 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0002_tracking_alter_usermodel_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this tracking entry (if created by an authenticated user)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trackings', to='buysellapi.usermodel'),
        ),
    ]
