# Generated by Django 5.2.7 on 2025-11-01 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0003_tracking_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(help_text='User who owns this permanent shipping mark', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_mark', to='buysellapi.usermodel')),
            ],
            options={
                'verbose_name': 'Shipping Mark',
                'verbose_name_plural': 'Shipping Marks',
                'ordering': ['-created_at'],
            },
        ),
    ]
