# Generated by Django 5.2.7 on 2025-11-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0004_shippingmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Cubic meters (e.g., 1.234)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='shipping_mark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
