# Generated by Django 5.2.7 on 2025-11-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0006_alter_usermodel_email_alter_usermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='contact',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
