# Generated by Django 5.2.7 on 2025-11-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0006_deduplicate_usermodel_emails'),
        ('buysellapi', '0007_alter_usermodel_contact'),
    ]

    operations = [
    ]
