# Generated by Django 5.2.7 on 2025-11-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0008_merge_20251101_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='action',
        ),
        migrations.AddField(
            model_name='tracking',
            name='eta',
            field=models.DateField(blank=True, help_text='Estimated Time of Arrival', null=True),
        ),
    ]
