# Generated by Django 5.2.7 on 2025-11-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0009_remove_tracking_action_tracking_eta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='shipping_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Shipping fee amount', max_digits=10, null=True),
        ),
    ]
