# Generated by Django 5.2.7 on 2025-11-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0010_tracking_shipping_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_goods_rate', models.DecimalField(decimal_places=2, help_text='Rate per CBM for normal goods in dollars', max_digits=10)),
                ('special_goods_rate', models.DecimalField(decimal_places=2, help_text='Rate per CBM for special goods in dollars', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rate is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Rate',
                'verbose_name_plural': 'Shipping Rates',
                'ordering': ['-created_at'],
            },
        ),
    ]
