# Generated by Django 5.2.7 on 2025-11-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0011_shippingrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingrate',
            name='normal_goods_rate_lt1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate for normal goods when CBM < 1 (flat or per-CBM as business rules)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='special_goods_rate_lt1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate for special goods when CBM < 1 (flat or per-CBM as business rules)', max_digits=10, null=True),
        ),
    ]
