# Generated by Django 5.2.7 on 2025-11-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0012_shippingrate_normal_goods_rate_lt1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='goods_type',
            field=models.CharField(blank=True, choices=[('normal', 'Normal Goods'), ('special', 'Special Goods')], help_text='Selected rate category for fee calculation', max_length=10, null=True),
        ),
    ]
