# Generated by Django 5.2.7 on 2025-11-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0013_tracking_goods_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('arrived', 'Arrived(China)'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('not_received', 'Not Received'), ('vessel', 'On The Vessel'), ('clearing', 'Clearing'), ('arrived_ghana', 'Arrived(Ghana)'), ('off_loading', 'Of Loading'), ('pick_up', 'Pick up')], default='pending', max_length=20),
        ),
    ]
