# Generated by Django 5.2.7 on 2025-11-01 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0014_update_status_arrived_ghana'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultBaseAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_address', models.TextField(help_text='Default base address template for address generation')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this is the currently active base address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Admin who last updated this address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_base_addresses', to='buysellapi.usermodel')),
            ],
            options={
                'verbose_name': 'Default Base Address',
                'verbose_name_plural': 'Default Base Addresses',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_id', models.CharField(db_index=True, help_text='Unique mark identifier (e.g., M856-FIM001)', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Recipient name', max_length=100)),
                ('full_address', models.TextField(help_text='Complete formatted shipping address')),
                ('shipping_mark', models.CharField(help_text="Formatted as 'markId:name'", max_length=200)),
                ('tracking_number', models.CharField(blank=True, default='', help_text='Optional associated tracking number', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipping_addresses', to='buysellapi.usermodel')),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shipping Addresses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mark_id'], name='buysellapi__mark_id_f56099_idx'), models.Index(fields=['created_at'], name='buysellapi__created_1225a4_idx')],
            },
        ),
    ]
