# Generated by Django 5.2.7 on 2025-11-02 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0015_defaultbaseaddress_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(help_text='The tracking number the user wants to follow', max_length=100)),
                ('user_shipping_mark', models.CharField(blank=True, default='', help_text="User's shipping mark at the time of adding (for reference)", max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text='User who added this tracking to their watchlist', on_delete=django.db.models.deletion.CASCADE, related_name='user_shipments', to='buysellapi.usermodel')),
            ],
            options={
                'verbose_name': 'User Shipment',
                'verbose_name_plural': 'User Shipments',
                'ordering': ['-date_added'],
                'unique_together': {('owner', 'tracking_number')},
            },
        ),
    ]
