# Generated by Django 5.2.7 on 2025-11-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0016_usershipment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserShipment',
        ),
    ]
