# Generated by Django 5.2.7 on 2025-11-02 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0017_delete_usershipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('tracking_update', 'Tracking Status Update'), ('tracking_created', 'New Tracking Created'), ('welcome', 'Welcome Email'), ('password_reset', 'Password Reset'), ('invoice_ready', 'Invoice Ready'), ('admin_announcement', 'Admin Announcement'), ('shipping_mark_created', 'Shipping Mark Created')], help_text='Type of notification', max_length=50)),
                ('subject', models.CharField(help_text='Email subject line', max_length=255)),
                ('message', models.TextField(help_text='Email body content')),
                ('html_message', models.TextField(blank=True, help_text='HTML version of the email', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When email was sent', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if send failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking', models.ForeignKey(blank=True, help_text='Related tracking if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='buysellapi.tracking')),
                ('user', models.ForeignKey(help_text='User who should receive this email', on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to='buysellapi.usermodel')),
            ],
            options={
                'verbose_name': 'Email Notification',
                'verbose_name_plural': 'Email Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='buysellapi__user_id_bd5266_idx'), models.Index(fields=['notification_type', 'created_at'], name='buysellapi__notific_fb441a_idx')],
            },
        ),
    ]
