# Generated by Django 5.2.7 on 2025-11-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0018_emailnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='notification_type',
            field=models.CharField(choices=[('tracking_update', 'Tracking Status Update'), ('tracking_created', 'New Tracking Created'), ('welcome', 'Welcome Email'), ('password_reset', 'Password Reset'), ('invoice_ready', 'Invoice Ready'), ('admin_announcement', 'Admin Announcement'), ('admin_notification', 'Admin Notification'), ('shipping_mark_created', 'Shipping Mark Created')], help_text='Type of notification', max_length=50),
        ),
    ]
