# Generated by Django 5.2.7 on 2025-11-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0019_alter_emailnotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('read', 'Read'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20),
        ),
    ]
