# Generated by Django 5.2.7 on 2025-11-02 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0020_alter_emailnotification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='notification_type',
            field=models.CharField(choices=[('tracking_update', 'Tracking Status Update'), ('tracking_created', 'New Tracking Created'), ('welcome', 'Welcome Email'), ('password_reset', 'Password Reset'), ('invoice_ready', 'Invoice Ready'), ('admin_announcement', 'Admin Announcement'), ('admin_notification', 'Admin Notification'), ('shipping_mark_created', 'Shipping Mark Created'), ('otp_login', 'Login OTP')], help_text='Type of notification', max_length=50),
        ),
        migrations.CreateModel(
            name='LoginOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Delivery email for this OTP', max_length=254)),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_otps', to='buysellapi.usermodel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='buysellapi__email_5cc689_idx'), models.Index(fields=['user', 'is_used'], name='buysellapi__user_id_6d07fd_idx')],
            },
        ),
    ]
