# Generated by Django 5.2.7 on 2025-11-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0022_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='notify_email',
            field=models.BooleanField(default=True, help_text='Receive general email notifications'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='notify_order_updates',
            field=models.BooleanField(default=True, help_text='Receive order/shipment update emails'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='notify_promotions',
            field=models.BooleanField(default=False, help_text='Receive promotional/marketing emails'),
        ),
    ]
