# Generated by Django 5.2.7 on 2025-11-04 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0023_usermodel_notify_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(db_index=True, help_text='Unique container identifier (e.g., CONT-2025-001)', max_length=64, unique=True)),
                ('port_of_loading', models.CharField(default='China', help_text='Port where container is loaded', max_length=100)),
                ('port_of_discharge', models.CharField(default='Ghana', help_text='Destination port', max_length=100)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('loading', 'Loading'), ('in_transit', 'In Transit'), ('arrived_port', 'Arrived at Port'), ('clearing', 'Clearing'), ('completed', 'Completed')], default='preparing', max_length=20)),
                ('departure_date', models.DateField(blank=True, help_text='When the container departs from China', null=True)),
                ('arrival_date', models.DateField(blank=True, help_text='Expected/actual arrival date in Ghana', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes or comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tracking',
            name='container',
            field=models.ForeignKey(blank=True, help_text='Container this tracking belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trackings', to='buysellapi.container'),
        ),
    ]
