# Generated by Django 5.2.7 on 2025-11-04 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0024_add_container_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, help_text='Unique invoice number (e.g., INV-2025-001)', max_length=64, unique=True)),
                ('shipping_mark', models.CharField(db_index=True, help_text="Customer's shipping mark ID", max_length=255)),
                ('customer_name', models.CharField(blank=True, help_text='Customer name for display', max_length=255)),
                ('customer_email', models.EmailField(blank=True, help_text='Customer email for invoice delivery', max_length=254)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all line items', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Final amount to be paid', max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('issue_date', models.DateField(blank=True, help_text='Date invoice was issued', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Payment due date', null=True)),
                ('paid_date', models.DateField(blank=True, help_text='Date payment was received', null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Method of payment (e.g., Bank Transfer, Cash)', max_length=50)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment transaction reference', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(help_text='Container this invoice is for', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='buysellapi.container')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to='buysellapi.usermodel')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Item description', max_length=255)),
                ('tracking_number', models.CharField(help_text='Tracking number for reference', max_length=64)),
                ('cbm', models.DecimalField(decimal_places=3, help_text='Cubic meters', max_digits=10)),
                ('rate_per_cbm', models.DecimalField(decimal_places=2, help_text='Rate per CBM at time of invoicing', max_digits=10)),
                ('goods_type', models.CharField(blank=True, help_text='Normal or Special goods', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total for this line item', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(help_text='Invoice this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='buysellapi.invoice')),
                ('tracking', models.ForeignKey(help_text='Tracking number this item is for', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='buysellapi.tracking')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['container', 'shipping_mark'], name='buysellapi__contain_8f875b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='buysellapi__status_0656fa_idx'),
        ),
    ]
