# Generated by Django 5.2.7 on 2025-11-05 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0025_add_invoice_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='tracking',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
