# Generated by Django 5.2.7 on 2025-11-05 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0029_add_invoice_paid_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='USD to GHS exchange rate at time of invoice creation', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount_ghs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount in GHS (Ghanaian Cedis)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final amount to be paid in USD', max_digits=10),
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_ghs', models.DecimalField(decimal_places=4, help_text='Current exchange rate: 1 USD = X GHS', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this rate update')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Admin who last updated the rate', null=True, on_delete=django.db.models.deletion.SET_NULL, to='buysellapi.usermodel')),
            ],
            options={
                'verbose_name': 'Currency Exchange Rate',
                'verbose_name_plural': 'Currency Exchange Rates',
                'ordering': ['-updated_at'],
            },
        ),
    ]
