# Generated by Django 5.2.7 on 2025-11-05 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0030_add_currency_rate_and_invoice_ghs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlipayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(blank=True, default='personal', max_length=32)),
                ('alipay_account', models.CharField(blank=True, default='', max_length=128)),
                ('real_name', models.CharField(blank=True, default='', max_length=128)),
                ('qr_code_image', models.TextField(blank=True, default='', help_text='URL or base64 image')),
                ('platform_source', models.CharField(blank=True, default='Alipay', max_length=64)),
                ('original_currency', models.CharField(default='CNY', max_length=16)),
                ('original_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('converted_currency', models.CharField(default='CEDI', max_length=16)),
                ('converted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Rate used for conversion', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=128)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who submitted/owns this payment (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alipay_payments', to='buysellapi.usermodel')),
            ],
            options={
                'verbose_name': 'Alipay Payment',
                'verbose_name_plural': 'Alipay Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='buysellapi__status_ecbfc9_idx')],
            },
        ),
    ]
