# Generated by Django 5.2.7 on 2025-11-05 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0031_alipaypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlipayExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghs_to_cny', models.DecimalField(decimal_places=4, help_text='CNY per 1 GHS', max_digits=10)),
                ('cny_to_ghs', models.DecimalField(decimal_places=4, help_text='GHS per 1 CNY', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this rate update')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Admin who last updated the Alipay rate', null=True, on_delete=django.db.models.deletion.SET_NULL, to='buysellapi.usermodel')),
            ],
            options={
                'verbose_name': 'Alipay Exchange Rate',
                'verbose_name_plural': 'Alipay Exchange Rates',
                'ordering': ['-updated_at'],
            },
        ),
    ]
