# Generated by Django 5.2.7 on 2025-11-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0032_alipayexchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alipayexchangerate',
            name='cny_to_ghs',
            field=models.DecimalField(decimal_places=3, help_text='GHS per 1 CNY', max_digits=10),
        ),
        migrations.AlterField(
            model_name='alipayexchangerate',
            name='ghs_to_cny',
            field=models.DecimalField(decimal_places=3, help_text='CNY per 1 GHS', max_digits=10),
        ),
        migrations.AlterField(
            model_name='alipaypayment',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Rate used for conversion', max_digits=10, null=True),
        ),
    ]
