# Generated by Django 5.2.7 on 2025-11-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0033_alter_alipayexchangerate_cny_to_ghs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='notification_type',
            field=models.CharField(choices=[('tracking_update', 'Tracking Status Update'), ('tracking_created', 'New Tracking Created'), ('welcome', 'Welcome Email'), ('password_reset', 'Password Reset'), ('invoice_ready', 'Invoice Ready'), ('invoice_paid', 'Invoice Payment Received'), ('admin_announcement', 'Admin Announcement'), ('admin_notification', 'Admin Notification'), ('shipping_mark_created', 'Shipping Mark Created'), ('otp_login', 'Login OTP'), ('alipay_payment_submitted', 'Alipay Payment Submitted'), ('alipay_payment_status', 'Alipay Payment Status Update')], help_text='Type of notification', max_length=50),
        ),
    ]
