# Generated by Django 5.2.7 on 2025-11-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0034_alter_emailnotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alipaypayment',
            name='proof_of_payment',
            field=models.TextField(blank=True, default='', help_text='URL or base64 image of payment proof'),
        ),
    ]
