# Generated by Django 5.2.7 on 2025-11-06 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0035_alipaypayment_proof_of_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy4meRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_url', models.URLField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('invoice_created', models.BooleanField(default=False)),
                ('invoice_number', models.CharField(blank=True, max_length=64, null=True)),
                ('invoice_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('images', models.JSONField(blank=True, default=list, null=True)),
                ('additional_links', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy4me_requests', to='buysellapi.usermodel')),
            ],
        ),
    ]
