# Generated by Django 5.2.7 on 2025-11-07 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('buysellapi', '0037_siteconfiguration_delete_buy4merequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=100, help_text='Ordering weight for the tab (lower appears first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='Groups that can see this tab', to='auth.group')),
                ('users', models.ManyToManyField(blank=True, help_text='Users that can see this tab', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Tab',
                'verbose_name_plural': 'Dashboard Tabs',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='SiteConfiguration',
        ),
    ]
