# Generated by Django 5.2.7 on 2025-11-09 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0043_alter_emailnotification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy4meRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Product title/name', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Product description')),
                ('product_url', models.URLField(blank=True, help_text='Link to the product', null=True)),
                ('additional_links', models.JSONField(blank=True, default=list, help_text='Additional product links with quantities')),
                ('images', models.JSONField(blank=True, default=list, help_text='Product images URLs')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Requested quantity')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the request', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Admin notes or customer notes')),
                ('invoice_created', models.BooleanField(default=False, help_text='Whether invoice has been created')),
                ('invoice_number', models.CharField(blank=True, help_text='Invoice number if invoice was created', max_length=64, null=True)),
                ('invoice_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', help_text='Invoice payment status', max_length=20)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Invoice amount', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who made this request', on_delete=django.db.models.deletion.CASCADE, related_name='buy4me_requests', to='buysellapi.usermodel')),
            ],
            options={
                'verbose_name': 'Buy4me Request',
                'verbose_name_plural': 'Buy4me Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
