# Generated by Django 5.2.7 on 2025-11-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0044_buy4merequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy4merequest',
            name='tracking_status',
            field=models.CharField(blank=True, choices=[('sourcing', 'Sourcing'), ('buying', 'Buying'), ('sent_to_warehouse', 'Sent to Warehouse'), ('shipped', 'Shipped'), ('at_the_port', 'At the Port'), ('off_loading', 'Off Loading'), ('pickup', 'Pickup')], help_text='Current tracking status of the request', max_length=20, null=True),
        ),
    ]
