# Generated by Django 5.2.7 on 2025-11-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0045_buy4merequest_tracking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='notification_type',
            field=models.CharField(choices=[('tracking_update', 'Tracking Status Update'), ('tracking_created', 'New Tracking Created'), ('welcome', 'Welcome Email'), ('password_reset', 'Password Reset'), ('invoice_ready', 'Invoice Ready'), ('invoice_paid', 'Invoice Payment Received'), ('admin_announcement', 'Admin Announcement'), ('admin_notification', 'Admin Notification'), ('shipping_mark_created', 'Shipping Mark Created'), ('otp_login', 'Login OTP'), ('alipay_payment_submitted', 'Alipay Payment Submitted'), ('alipay_payment_status', 'Alipay Payment Status Update'), ('order_placed', 'Order Placed'), ('order_confirmation', 'Order Confirmation'), ('buy4me_order_placed', 'Buy4Me Order Placed'), ('buy4me_order_confirmation', 'Buy4Me Order Confirmation')], help_text='Type of notification', max_length=50),
        ),
    ]
