# Generated by Django 5.2.7 on 2025-11-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellapi', '0046_alter_emailnotification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Product title/name', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Product description')),
                ('product_url', models.URLField(help_text='Link to the product')),
                ('images', models.JSONField(blank=True, default=list, help_text='Product images URLs')),
                ('min_quantity', models.PositiveIntegerField(default=20, help_text='Minimum quantity for this product')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is active and visible to users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quick Order Product',
                'verbose_name_plural': 'Quick Order Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
